<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AssemblyName>fwin</AssemblyName>
		<RootNamespace>FreshWin.Cli</RootNamespace>
		<Product>FreshWin</Product>
		<Description>An all-in-one utility to speed up Windows 11 fresh installs, "back up, customize image, restore".</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FreshWin.Backup\FreshWin.Backup.csproj" />
		<ProjectReference Include="..\FreshWin.Deployment\FreshWin.Deployment.csproj" />
	</ItemGroup>

</Project>
